# Page settings

baseurl = "https://github.com/ErkinSemiz/cv.erkinsemiz.com/tree/master/"
languageCode = "en-us"
title = "Erkin Semiz Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = false
disableSitemap = false
disable404 = false

[params]

# Meta
    description = "Erkin Semiz CV"
    author = "Erkin Semiz"
    avatar = "avatar.png"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Erkin Semiz"
        tagline = "Software Developer"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: erkin1semiz@gmail.com"
        title = "erkin1semiz@gmail.com"


        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/erkinsemiz"
        title = "linkedin.com/in/erkinsemiz"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/erkinsemiz"
        title = "github.com/erkinsemiz"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Computer Engineering"
        college = "Eskisehir Osmangazi University"
        dates = "Expected Graduation June 2019"

        [[params.education.list]]
        degree = "BSc in Electrical and Electronics Engineering"
        college = "Eskisehir Osmangazi University"
        dates = "Expected Graduation June 2020"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Turkish"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "French"
        level = "Beginner"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

	[[params.interests.list]]
        interest = "Industry 4.0"

        [[params.interests.list]]
        interest = "Traditional Archery"

	[[params.interests.list]]
        interest = "Artificial Intelligence"

	[[params.interests.list]]
        interest = "Basketball"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

     # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Co-Founder"
        dates = "2016 - Present"
        company = "Team Beta"
        details = "With my fellow university friends we wanted to start a Organization to create a space for our imagination and projects which improves our vision. This organizaton is not only for few people, it's all of us. https://github.com/TeamBetaOgu "

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = ""

        [[params.projects.list]]
        title = "Automated Guided Vehicle and Katana Arm Scenario Simulation"
        url = "https://github.com/ErkinSemiz/agvs_katana_simulation"
        tagline = "Appropriate expectation of the future's requirements and Industry 4.0 revolution, base level communication between carrier and automated arm with ROS and Gazebo Simulation"
        
	[[params.projects.list]]
        title = "Online Book Store Application with User Database"
        url = "https://github.com/ErkinSemiz/OOP2_Term_Project"
        tagline = "Based On C# language and developed for the OOP II project for the Eskisehir Osmangazi University.Main goal is developing alive book store application with popular patterns, tools and design with digital arts."

   
    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
